// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage

module.exports = {
  'default e2e tests': browser => {
    browser
            .setWindowPosition(0, 0)
            .pause(10000)
            .frameParent()
            .resizeWindow(1000, 800)
            .pause(10000)
            .url('http://localhost:3001/#/')
            .waitForElementVisible('#app', 5000)
            .assert.elementPresent('body')
            .pause(1000)
            .click('a[href="/#/show"]')
            .waitForElementVisible('span[value="1002"]', 5000)
            .pause(1000)
            .moveTo('span[value="1002"]')
            .click('span[value="1002"]')
            .click('span[value="1001"]')
            .click('span[value="1003"]')
            .click('span[value="1004"]')
            .click('span[value="1002"]')
            .click('span[value="1001"]')
            .click('span[value="1003"]')
            .click('span[value="1004"]')
            .click('span[value="1002"]')
            .click('span[value="1001"]')
            .pause(1000)
            .click('span[value="1003"]')
            .pause(1000)
            .click('span[value="1004"]')
            .pause(1000)
            .click('span[value="1002"]')
            .pause(1000)
            .click('span[value="1001"]')
            .pause(1000)
            .click('span[value="1003"]')
            .pause(1000)
            .click('span[value="1004"]')
            .pause(1000)
            .click('span[value="1002"]')
            .pause(1000)
            .click('span[value="1001"]')
            .pause(1000)
            .click('span[value="1003"]')
            .pause(1000)
            .click('span[value="1004"]')

        // .assert.containsText('a', 'PLATO')
        // .assert.containsText('a', 'Show')
        // there is no router-view tag in vue 2
        // .assert.elementCount('.router-view', 0)
        // .end()
  }
}
